# Data Analysis - IT Helpdesk Tickets
<br/>
Most names have been encrypted to help protect personal data.  Some names were replaced with randomly generated names, using the following name generator:<br/>
Fossbytes Name Generator<br/>
https://fossbytes.com/tools/random-name-generator<br/>

In [1]:
import numpy as np
import pandas as pd

In [2]:
#df1 = pd.read_csv('Requests_older_than_2019--FIXED.csv')
#df2 = pd.read_csv('Requests_greater_than_equal_2019--FIXED.csv')

In [3]:
#df1 = pd.read_csv('Requests_older_than_2019--ENCRYPTED.csv')
#df2 = pd.read_csv('Requests_greater_than_equal_2019--ENCRYPTED.csv')

In [4]:
df = pd.read_csv('Requests-before-2023.csv')

In [5]:
df = df.set_index('Request ID')
df = df.sort_index(ascending=True)

In [6]:
#df = pd.concat([df1, df2])
#df = df.set_index('Request ID')
#df = df.sort_index(ascending=True)

In [7]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9562 entries, 9067 to 20479
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Subject               9562 non-null   object
 1   Branch or Department  9562 non-null   object
 2   Created Date          9562 non-null   object
 3   Resolved Date         9562 non-null   object
 4   Last Update Time      9562 non-null   object
 5   DueBy Date            9562 non-null   object
 6   Completed Date        9562 non-null   object
 7   Requester             9562 non-null   object
 8   Technician            9562 non-null   object
 9   Priority              9562 non-null   object
 10  Status                9562 non-null   object
dtypes: object(11)
memory usage: 896.4+ KB

,Subject,Branch or Department,Created Date,Resolved Date,Last Update Time,DueBy Date,Completed Date,Requester,Technician,Priority,Status
Request ID,,,,,,,,,,,
9067,Locke's TVs in open area don't work,-,"Feb 21, 2016 06:28 PM","Feb 21, 2016 06:28 PM",-,-,"Feb 21, 2016 06:28 PM","Kinkus, Mary",Duane Ackley,-,Closed
9068,PopTeen: iMac #12,-,"Feb 21, 2016 06:28 PM","Apr 1, 2016 12:32 PM","Apr 1, 2016 12:32 PM",-,"Apr 1, 2016 12:32 PM","Lutz, David","Krasa, Tom",-,Closed
9069,Ext. 5264 Answers on Speakerphone,-,"Feb 21, 2016 06:28 PM","Feb 21, 2016 06:28 PM",-,-,"Feb 21, 2016 06:28 PM","Hebert, Gayle",-,-,Closed
9070,pc 18 in Pop/Teen,-,"Feb 21, 2016 06:28 PM","Feb 21, 2016 06:28 PM",-,-,"Feb 21, 2016 06:28 PM","Shriner, Martin","Krasa, Tom",-,Closed
9071,bad copies of windows in Pop/Teen,-,"Feb 21, 2016 06:28 PM","Mar 22, 2016 11:27 AM","Mar 22, 2016 11:27 AM",-,"Mar 22, 2016 11:27 AM","Shriner, Martin","Krasa, Tom",-,Closed

In [8]:
df['Created Date'] = pd.to_datetime(df['Created Date'])
df['Resolved Date'] = pd.to_datetime(df['Resolved Date'], errors='coerce')
#df['DueBy Date'] = pd.to_datetime(df['DueBy Date'], errors='coerce')
df['Completed Date'] = pd.to_datetime(df['Completed Date'], errors='coerce')
#df['Last Update Time'] = pd.to_datetime(df['Last Update Time'], errors='coerce')

In [9]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9562 entries, 9067 to 20479
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Subject               9562 non-null   object
 1   Branch or Department  9562 non-null   object
 2   Created Date          9562 non-null   datetime64[ns]
 3   Resolved Date         9534 non-null   datetime64[ns]
 4   Last Update Time      9562 non-null   object
 5   DueBy Date            9562 non-null   object
 6   Completed Date        9523 non-null   datetime64[ns]
 7   Requester             9562 non-null   object
 8   Technician            9562 non-null   object
 9   Priority              9562 non-null   object
 10  Status                9562 non-null   object
dtypes: datetime64[ns](3), object(8)
memory usage: 896.4+ KB

,Subject,Branch or Department,Created Date,Resolved Date,Last Update Time,DueBy Date,Completed Date,Requester,Technician,Priority,Status
Request ID,,,,,,,,,,,
9067,Locke's TVs in open area don't work,-,2016-02-21 18:28:00,2016-02-21 18:28:00,-,-,2016-02-21 18:28:00,"Kinkus, Mary",Duane Ackley,-,Closed
9068,PopTeen: iMac #12,-,2016-02-21 18:28:00,2016-04-01 12:32:00,"Apr 1, 2016 12:32 PM",-,2016-04-01 12:32:00,"Lutz, David","Krasa, Tom",-,Closed
9069,Ext. 5264 Answers on Speakerphone,-,2016-02-21 18:28:00,2016-02-21 18:28:00,-,-,2016-02-21 18:28:00,"Hebert, Gayle",-,-,Closed
9070,pc 18 in Pop/Teen,-,2016-02-21 18:28:00,2016-02-21 18:28:00,-,-,2016-02-21 18:28:00,"Shriner, Martin","Krasa, Tom",-,Closed
9071,bad copies of windows in Pop/Teen,-,2016-02-21 18:28:00,2016-03-22 11:27:00,"Mar 22, 2016 11:27 AM",-,2016-03-22 11:27:00,"Shriner, Martin","Krasa, Tom",-,Closed

In [10]:
df.Technician.unique()

array(['Duane Ackley', 'Krasa, Tom', '-', 'Dave Misko', 'Shazad Bakhsh',
       'Jonathan Hoover', 'Roxanna Foster', 'Jeff Wale', 'Ben Bolbach',
       'Tom Gray', 'Administrator', 'Alyssa Burke', 'IT Tech',
       'Andy Lechlak', 'Donna Spychala', 'Kristie Lanzotti',
       'Collins Onyia'], dtype=object)

In [11]:
df.Technician.value_counts()

Jonathan Hoover     2977
Alyssa Burke        1693
Duane Ackley        1280
-                   1065
Shazad Bakhsh        942
Collins Onyia        414
Krasa, Tom           324
Roxanna Foster       315
Dave Misko           306
IT Tech              124
Ben Bolbach           92
Andy Lechlak          14
Jeff Wale             10
Tom Gray               3
Administrator          1
Donna Spychala         1
Kristie Lanzotti       1
Name: Technician, dtype: int64

In [13]:
df_agency = df['Branch or Department'].value_counts()
df['Branch or Department'].value_counts()

-                                        2291
WEST TOLEDO                               517
SANGER                                    408
KING ROAD                                 400
REYNOLDS CORNERS                          344
OREGON                                    336
SYLVANIA                                  298
HOLLAND                                   275
MOTT                                      267
WASHINGTON                                260
LAGRANGE                                  259
Technical Services                        252
LOCKE                                     249
WATERVILLE                                222
KENT                                      222
Local History                             217
Fact and Fiction                          200
Computers and Media                       192
HEATHERDOWNS                              188
TOLEDO HEIGHTS                            187
BIRMINGHAM                                174
MAUMEE                                    171
POINT PLACE                               152
Teen / Making Space                       143
Children's Library                        138
Main Circulation                          136
SOUTH                                     111
Marketing                                 100
MOBILE SERVICES                            80
Director's Office                          72
Children's Library/Teen Library-Metro      63
Human Resources                            63
Youth Services                             55
Humanities                                 53
Development Office                         42
OUTREACH                                   39
Public Services                            38
Facilities & Operations                    36
Cherry Street Mission                      36
Business Technology                        33
Finance                                    28
Business and Workforce Development         28
Main Library Manager                       27
Popular Library                            25
Branch Services                            23
Audio/Visual                               23
Security                                   22
Information Technology                     20
Adult Services                             18
Friends of the Library                     13
Read for Literacy                           9
Classics Gift Shop                          3
Institutional & Community Initiatives       2
Virtual Services                            1
External and Governmental Affairs           1
Name: Branch or Department, dtype: int64

In [20]:
df[df['Branch or Department'] != '-']

,Subject,Branch or Department,Created Date,Resolved Date,Last Update Time,DueBy Date,Completed Date,Requester,Technician,Priority,Status
Request ID,,,,,,,,,,,
11435,Events on Screen at Waterville,WATERVILLE,2017-07-25 16:25:00,2017-08-02 14:03:00,"Aug 2, 2017 08:55 AM","Jul 26, 2017 12:25 AM",2017-08-02 14:03:00,William Harbauer,Roxanna Foster,Low,Closed
11448,Children's PC 2,WEST TOLEDO,2017-07-27 15:18:00,2017-07-28 10:21:00,"Jul 28, 2017 10:21 AM",-,2017-07-28 10:21:00,barb.trevino@toledolibrary.org,Alyssa Burke,-,Closed
11450,Barcode scanner on selfcheck not working,HEATHERDOWNS,2017-07-27 15:50:00,2017-08-03 13:26:00,"Aug 3, 2017 01:26 PM","Jul 27, 2017 04:50 PM",2017-08-03 13:26:00,James McCann,Alyssa Burke,High,Closed
11451,Sanger OPAC1,SANGER,2017-07-27 16:31:00,2017-07-28 12:18:00,"Jul 28, 2017 12:18 PM","Jul 27, 2017 08:31 PM",2017-07-28 12:18:00,Katie Midgley,Duane Ackley,Normal,Closed
11452,South--Celeste unable to access August schedul...,SOUTH,2017-07-27 16:44:00,2017-07-28 09:31:00,"Jul 28, 2017 09:31 AM","Jul 27, 2017 05:44 PM",2017-07-28 09:31:00,Celeste Taylor,Alyssa Burke,High,Closed
...,...,...,...,...,...,...,...,...,...,...,...
20474,Waterville Zoom Account,WATERVILLE,2022-12-29 18:29:00,2022-12-30 10:52:00,"Dec 30, 2022 10:52 AM","Dec 29, 2022 08:29 PM",2022-12-30 10:52:00,Abby Byers,Jonathan Hoover,Medium,Closed
20475,Internet PC 2 Mouse Issue,Children's Library,2022-12-29 18:51:00,NaT,"Jan 3, 2023 09:02 AM",-,NaT,Sara Mattson,Jonathan Hoover,-,Open
20477,F&F Scan Station,Fact and Fiction,2022-12-30 10:20:00,2023-01-03 11:01:00,"Jan 3, 2023 11:01 AM",-,2023-01-03 11:01:00,franco.vitella@toledolibrary.org,Shazad Bakhsh,-,Closed
20478,OPAC down,LAGRANGE,2022-12-30 12:12:00,NaT,"Jan 3, 2023 09:02 AM","Dec 30, 2022 04:12 PM",NaT,Katie Midgley,Jonathan Hoover,Normal,Open
20479,Color copies,SYLVANIA,2022-12-30 16:07:00,2023-01-03 10:07:00,"Jan 3, 2023 10:07 AM","Dec 30, 2022 05:07 PM",2023-01-03 10:07:00,Wendy Ponder,Alyssa Burke,High,Closed

In [19]:
df_agency.to_csv('helpdesk-tickets-by-agency.csv')

<p><b>The following will select all helpdesk tickets created in the year 2020.  It will then group them by the Branch or Department and show how many tickets each one had that year, sorted in descending order.</b></p>
<p><b>This can be done for each year and gives us very useful information about which branches have more reported technology issues, and how these numbers change over time.</b></p>

In [14]:
df_2020 = df[df['Created Date'].dt.year == 2020]

In [15]:
df_2020.head()

,Subject,Branch or Department,Created Date,Resolved Date,Last Update Time,DueBy Date,Completed Date,Requester,Technician,Priority,Status
Request ID,,,,,,,,,,,
15685,public bw printing legal as default,SYLVANIA,2020-01-02 09:40:00,2020-01-02 10:26:00,"Jan 2, 2020 10:26 AM",-,2020-01-02 10:26:00,Peter Hildebrandt,Jonathan Hoover,-,Closed
15686,Images in Time is Down,Local History,2020-01-02 10:25:00,2020-01-02 11:47:00,"Jan 2, 2020 11:47 AM","Jan 2, 2020 02:25 PM",2020-01-02 11:47:00,John Dewees,Shazad Bakhsh,Normal,Closed
15687,obituary request link is down,Local History,2020-01-02 10:58:00,2020-01-02 11:41:00,"Jan 2, 2020 11:41 AM","Jan 2, 2020 11:58 AM",2020-01-02 11:41:00,veronica.mitchell@toledolibrary.org,Shazad Bakhsh,High,Closed
15688,Database Maintenance for obituaries is down,Local History,2020-01-02 11:02:00,2020-01-02 11:40:00,"Jan 2, 2020 11:40 AM","Jan 2, 2020 12:02 PM",2020-01-02 11:40:00,veronica.mitchell@toledolibrary.org,Shazad Bakhsh,High,Closed
15689,Install Vidbox Software on Media Conversion PC...,Teen / Making Space,2020-01-02 11:28:00,2020-03-06 14:20:00,"Mar 6, 2020 02:20 PM",-,2020-03-06 14:20:00,"Kramer, Rebecca",Shazad Bakhsh,-,Closed

In [16]:
df_2020['Branch or Department'].value_counts()

WEST TOLEDO                           108
SANGER                                 77
Computers and Media                    70
Technical Services                     69
Fact and Fiction                       67
KING ROAD                              67
REYNOLDS CORNERS                       59
HOLLAND                                57
SYLVANIA                               49
OREGON                                 49
BIRMINGHAM                             48
WASHINGTON                             47
TOLEDO HEIGHTS                         43
KENT                                   42
LOCKE                                  40
MOTT                                   40
LAGRANGE                               40
WATERVILLE                             32
Local History                          30
Teen / Making Space                    30
MAUMEE                                 28
POINT PLACE                            27
HEATHERDOWNS                           26
MOBILE SERVICES                        26
Human Resources                        24
Children's Library                     23
Marketing                              21
Main Circulation                       16
Public Services                        14
Branch Services                        10
Director's Office                       9
Adult Services                          6
Friends of the Library                  6
Business and Workforce Development      5
Finance                                 5
Security                                5
SOUTH                                   5
Youth Services                          4
Development Office                      3
Information Technology                  3
Cherry Street Mission                   2
Main Library Manager                    1
Facilities & Operations                 1
Name: Branch or Department, dtype: int64

In [13]:
df['Branch or Department'].unique().shape

(55,)

In [17]:
# Columns are dates (month-year)
df['month_year_created'] = df['Created Date'].dt.to_period('M')

df['month_year_created'].head(10)

Request ID
9067    2016-02
9068    2016-02
9069    2016-02
9070    2016-02
9071    2016-02
9072    2016-02
9073    2016-02
9074    2016-02
9075    2016-02
9076    2016-02
Name: month_year_created, dtype: period[M]

In [18]:
# Rows are Agencies
rows_branch = df['Branch or Department'].unique()

In [19]:
rows_branch

array(['-', 'WATERVILLE', 'WEST TOLEDO', 'HEATHERDOWNS', 'SANGER',
       'SOUTH', 'SYLVANIA', 'HOLLAND', 'Audio/Visual', 'Humanities',
       'KING ROAD', 'LOCKE', "Director's Office", 'Technical Services',
       'MOTT', 'OREGON', 'BIRMINGHAM', 'KENT', 'Security',
       "Children's Library/Teen Library-Metro", 'TOLEDO HEIGHTS',
       'MAUMEE', 'REYNOLDS CORNERS', 'Local History', 'Popular Library',
       'OUTREACH', 'Marketing', 'WASHINGTON', 'Main Circulation',
       'LAGRANGE', 'POINT PLACE', 'Information Technology',
       'Business Technology', 'Main Library Manager', 'Branch Services',
       'Classics Gift Shop', 'Virtual Services', 'Human Resources',
       'Read for Literacy', 'Youth Services', 'Development Office',
       'Cherry Street Mission', 'Finance', 'Facilities & Operations',
       'Friends of the Library', 'MOBILE SERVICES', 'Adult Services',
       'Institutional & Community Initiatives', 'Teen / Making Space',
       'Computers and Media', "Children's Library", 'Fact and Fiction',
       'Business and Workforce Development', 'Public Services',
       'External and Governmental Affairs'], dtype=object)